### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by giutrec**
Added a Italian translation

Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [x] Improvement of an existing Feature 
  * [ ] New Feature

### CODE REVIEW

**Comment by denysvitali** [comment]
Dear @giutrec / Caro @giutrec ,
the italian translations are already available on https://crowdin.com/project/fusioninvoice/it - this project doesn't track any translation whatsoever since they're already created via crowdin.  
  
These translations are automatically included when a new version of InvoicePlane is released.

**Comment by Kovah** [comment]
Not entirely correct. The translations seem to be for the new InvoicePlane 2 version based on FusionInvoice.

However, yes: translations are not managed in this repo. I will set up Crowdin for InvoicePlane 2 shortly.

**Comment by denysvitali** [comment]
Uh my bad, I missed the branch!

**Comment by giutrec** [comment]
;)

**Comment by giutrec** [comment]
Sure, no problem i've already done it.

Regards

Il giorno 13 giu 2018, 13:24, alle ore 13:24, Kovah <notifications@github.com> ha scritto:

**Comment by Kovah** [comment]
Awesome! Many many thanks for the translation! 👍

**Pull request closed without merging**
