### PR TITLE
IP-537

### PR DESCRIPTION
**Pull request by aalwash**
Form validation was failing, because client_id was missing

### CODE REVIEW

**Comment by Kovah** [comment]
Thanks for your work!
Users also reported that credit invoices do not work either. Did you checked this?

**Comment by aalwash** [comment]
As in, copy invoice doesn't work? I just tested it, works fine for me

**Comment by Kovah** [comment]
Okay, maybe this is another issue, will check this out.

Really appreciate oyur work, many thanks!

**Comment by aalwash** [comment]
You're welcome! 

I enjoy this open source software, so sometimes helping the community back isn't a bad thing ;)

**Pull request merged**
