### PR TITLE
[IP-1083]: Add pagination for tabs in client detail

### PR DESCRIPTION
**Pull request by pumpi**
## Description
This PR add the function to paginate in clients detail the tabs for quotes invoices and payments

## Related Issue

#1083 

## Motivation and Context

If a client have more than 20 invoices, payments or quotes, only the newest 20 was shown

## Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request.
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.

## Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature
  * [x] New Feature

### CODE REVIEW

**Comment by pumpi** [comment]
@nielsdrost7 I don't know if this is the right way to integrate pagination, but I test it and it works. If you have some corrections, I will do it.

**Comment by nielsdrost7** [comment]
@pumpi I'm a bit worried about that $tab variable, I have to look at it on a bigger screen before I can approve this one ok?

**Comment by pumpi** [comment]
Yeah no problem it was the simplest solution for me but I think is not the best 🙈

**Review by naui95 — APPROVED** [review]
`$tab` solution works for me. We do not have any ajax pagination in IPv1 so that the provided solution is consistent with the project. I changed how we handle the "tab change event". The change made front-end with `js` had the problem that with the `$tab` solution the url did not match the current selection. To prevent this mismatch all tab clicks are now routing events.

**Comment by pumpi** [comment]
I have seen a styling issue last week. If you have a small display and must scroll to the pagination there is no space at the end of the page, this shows ugly. I wanted to fix it but couldn't find the time. I hope to have a few minutes next week. For the naming of `$tab` we can change it to `$activeTab` to make it clear what this variable does.

**Comment by naui95** [comment]
> I have seen a styling issue last week. If you have a small display and must scroll to the pagination there is no space at the end of the page, this shows ugly. I wanted to fix it but couldn't find the time. I hope to have a few minutes next week. For the naming of `$tab` we can change it to `$activeTab` to make it clear what this variable does.

Ok, thank you. I will put it on hold and wait for your integration before merging. Please remember to pull before starting with your edits ;)

**Comment by naui95** [comment]
Hi @pumpi do you have time to finish your PR? We would like to pull the solution in the next version. If not, I can check that design issue you mentioned.

**Comment by pumpi** [comment]
No sorry no time the last weeks. I'll do it tomorrow I promise. When are you planing the next release?

**Comment by naui95** [comment]
> No sorry no time the last weeks. I'll do it tomorrow I promise. When are you planing the next release?

beta release is planned for mid November (latest). If we get there before, then better :)

**Comment by pumpi** [comment]
@naui95 I have added a bottom space to `model-pager` if he is inside a tab to give him space in the footer. I also rename the `$tab`variable to `$activeTab` to make it clearer what it is used for.

**Review by nielsdrost7 — APPROVED** [review]
@pumpi Great job! Merged.

**Pull request merged**
