### PR TITLE
Fix for IP-434

### PR DESCRIPTION
**Pull request by nerok**
Added a \&nbsp; between invoice and invoice_number.

### CODE REVIEW

**Comment by Kovah** [comment]
Btw: is the space also missing in the quote screen?

**Comment by nerok** [comment]
Nope, but i forgot to check how it was done there

**Comment by nerok** [comment]
`<h2><?php echo trans('quote') . ' ' . $quote->quote_number; ?></h2>`

**Comment by Kovah** [comment]
Looks good. You just got your first pull request merged! 🎉

**Pull request merged**
