### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by dploeger**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [x] Improvement of an existing Feature 
  * [ ] New Feature

### CODE REVIEW

**Comment by dploeger** [comment]
If you accept this, you can also call me up on new or updated translations.

**Comment by Kovah** [comment]
Hope you didn't do the whole translation on your own. 😅 
German is already 100% translated: https://crowdin.com/project/invoiceplane

**Comment by dploeger** [comment]
ARGH. Yes, I did. Could you please document that somewhere so somebody else gets pointed in the right way? Thanks.

**Comment by Kovah** [comment]
What would be a good place to point to the translations?

**Comment by dploeger** [comment]
I would've expected it either in the README.md or in the Translations-chapter in the Wiki (I guess, that's still more or less the FusionInvoice-stuff, right?)

**Pull request closed without merging**
