### PR TITLE
CodeIgniter v3 + partial custom_values support

### PR DESCRIPTION
**Pull request by denysvitali**
I've partially implemented field_type + custom_values to allow a "single-choice" / "multi-choice" / "date" input.

The code base is now updated to CodeIgniter 3, it seems stable but it might be needed to check that every feature works as intended before merging

See the screenshots for a quick overview: in this example I've added a "Sex" custom field, and I've set it to "Single Choice", then I created two allowed values for this field: "Maschio" (Male) and "Femmina" (female).

screenshot from 2017-01-31 13-40-17
screenshot from 2017-01-31 13-39-57
screenshot from 2017-01-31 13-39-41

### CODE REVIEW

**Comment by Kovah** [comment]
Changed the target branch to work on this in the next days without having to push to your repo.

**Comment by denysvitali** [comment]
I'm gonna post it here real quick cause I have to go. I'll add it to a commit when I return home:
```sql
CREATE TABLE `ip_custom_values` (
  `custom_values_id` int(11) NOT NULL,
  `custom_values_field` int(11) NOT NULL,
  `custom_values_value` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ip_custom_values`
--
ALTER TABLE `ip_custom_values`
  ADD PRIMARY KEY (`custom_values_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ip_custom_values`
--
ALTER TABLE `ip_custom_values`
  MODIFY `custom_values_id` int(11) NOT NULL AUTO_INCREMENT;
```

Directly exported from PMA, not nice, but should work

**Comment by Kovah** [comment]
Cool, seems to be working without problems. Have to continue testing tomorrow and then merge the branches.

**Comment by denysvitali** [comment]
Please note that this is still WIP: custom fields are added to the database, but could not be used yet

**Comment by Kovah** [comment]
Ah okay, sounds good. Then I'll wait with the merge.

**Comment by denysvitali** [comment]
If you keep it in 1.4.11 and you don't release it yet, it would be better if you merge it, since this PR involves CodeIgniter 3 too. It may cause a huge headache to solve code conflicts problem if more files are changed without first merging this.

Let me know how do you want to proceed

**Comment by denysvitali** [comment]
Wonderful. Today I'll continue (and hope to finish) this module

**Comment by Kovah** [comment]
So, I merged into the pr-431 branch with some additional changes. maybe you could pull these changes before you continue.

Thanks for the good work! 👍

**Comment by denysvitali** [comment]
Wonderful. I'll do it!

**Comment by denysvitali** [comment]
Watch out, modules/units/models/mdl_units.php should be renamed Mdl_units.php (in Code Igniter 3 model names start always with an uppercase letter)

**Pull request merged**
