### PR TITLE
show (http(s)) protocol in setup complete procedure

### PR DESCRIPTION
**Pull request by nerdoc**
this way you can directly copy/paste the string into your .htaccess file.

### CODE REVIEW

**Comment by nerdoc** [comment]
Oh. I don't know hot the github pull requests work exactly. I don't want to push 4 commits to the origin's development branch. It should appear as one commit, it's only one file changed. Else please ignore/decline this request.

**Comment by Pitma** [comment]
Should work fine!
Am 16.07.2015 00:33 schrieb "Christian González" <notifications@github.com>:

**Comment by nerdoc** [comment]
I think next time I'll do that completely local, without the clicks/pull requests within my private forks on github. this is much work. Rebasing etc. is much more straightforward @home.

**Comment by Pitma** [comment]
But in general it is no problem! Each commit is trackable
Am 16.07.2015 00:37 schrieb "Christian González" <notifications@github.com>:

**Comment by nerdoc** [comment]
Eh - but here I have the "merge" commits as well. @home I can at least to a rebasing before to have a clean status of upstream. But I must admit I haven't wrapped my brain around git this far by now. ;-)

**Comment by Pitma** [comment]
This is not the easiest ;) but 4 commits are not a problem!  automatic
Rebasing is a nice thing!  And you should do it before pushing your
commits! Still struggling with some git issues ;P
Am 16.07.2015 00:41 schrieb "Christian González" <notifications@github.com>:

**Pull request merged**
