### PR TITLE
Issue/143/use country key for user country setting

### PR DESCRIPTION
**Pull request by miquel-cabanas**
Replaces pull-request #138 "Use country key instead of country value for user-country setting" that was closed by mistake. See discussion on the old pull-request.

### CODE REVIEW

**Comment by Kovah** [comment]
@Jadaw1n Could you take a look at it? :smile:

**Comment by Jadaw1n** [comment]
There are more fields which are based on this setting. I'm updating them also to use the new setting.

**Comment by miquel-cabanas** [comment]
Also we must check the language file before loading it to be sure it contains the `$lang['cldr'] = 'en';` line at the top, and otherwise discard loading it and warn the user to update it.

**Comment by Jadaw1n** [comment]
Good point. But I think this can be generalised, because there are a few new language strings. 
Do you think a warning + link in the setup would suffice?

**Comment by miquel-cabanas** [comment]
I would check the language files during setup but also when running the application, just in case a user copies a bad file afterwards.

**Comment by Jadaw1n** [comment]
At runtime: Would require lang() to somehow notify other functions... Can't really see a clean way here. I'd rather have the language string of the base language (english) displayed. This way the user can still use the application even if a particular string is displayed in english.

**Comment by jyrkij** [comment]
I vote for falling back to base language in case a translation isn't found. But can `cldr` have a fallback?

**Comment by Jadaw1n** [comment]
`cldr` is at this time only used to include a translated list of country names. If `cldr` falls back to `en`, then those are shown in English.

**Pull request merged**
