### PR TITLE
[IP-1012]: Revert change to invoice_logo() 

### LINKED ISSUE #1012: Web invoice does not show logo
## Expected Behavior
The invoice's web view uses invoice_logo() in invoice_helper.php, this function should provide a URL to the IP configured logo

## Current Behavior
invoice_logo() produces an invalid URL based on an absolute file system path, it seems this change was only intended for invoice_logo_pdf()

## Possible Solution
#1013

### PR DESCRIPTION
**Pull request by jmclaren7**
invoice_logo() produces an invalid URL based on an absolute file system path, it seems this change was only intended for invoice_logo_pdf()

Related issue: #1012

### CODE REVIEW

**Review by Computer-Ron — APPROVED** [review]
I am a novice interacting with GitHub so apologize in advance if not following proper procedure and/or protocol. I have implemented this change on my 1.6.1 installation and can report this change indeed resolves the logo not showing on email invoices issue by using the correct path for finding the file on the server (base vs absolute).

**Comment by jmclaren7** [comment]
Thanks @Computer-Ron for confirming you had a good result with the change, someone with access to the repository needs to make the review for it to automatically merge but maybe your input will prompt @nielsdrost7 to lend a hand, thanks!

**Comment by nielsdrost7** [comment]
@jmclaren7 merged!

@Computer-Ron thanks for the PR, man! Keep'em coming

**Review by jmmeijer — COMMENTED** [review]
This is correct, thanks

**Pull request merged**
