### PR TITLE
Fix for output of Japanese font which was not displayed correctly

### PR DESCRIPTION
**Pull request by kusanaginoturugi**
PDF出力した日本語フォントが正しく表示されていなかったので、設定を追加しました。

### CODE REVIEW

**Comment by Kovah** [comment]
Could you please change the title to english and add a quick description?

**Comment by Kovah** [comment]
@kusanaginoturugi

**Comment by You85** [comment]
Translation : "The output Japanese font was not displayed correctly, so the setting was added."

**Comment by miquel-cabanas** [comment]
There is now an issue for this PR:

IP-737 - Fix display of some non-Latin characters in mPDF generated PDF files
https://development.invoiceplane.com/browse/IP-737

**Pull request closed without merging**
