### PR TITLE
IP-301 refix Special character in Client Name breaks invoice/quote

### PR DESCRIPTION
**Pull request by mmilidoni**
When submit the invoice creation frame, the apostrophe on client name did produce a new client with only left split of client name.

### CODE REVIEW

**Comment by Kovah** [comment]
@mmilidoni Please rebase your commit on the latest development branch to remove duplicate commits.

**Comment by Kovah** [comment]
@mmilidoni ?

**Comment by mmilidoni** [comment]
I tried to make rebase but there are many conflicts. How can I apply changes without rebase? Maybe, do I can change development branch, directly?

**Comment by ayman-alkom** [comment]
@Kovah I suggest you ti remove the development branch and let the contributors  directly to push to master.
Just a suggestion, because I saw a lot of failed PR because of that.

**Comment by Kovah** [comment]
The pull requests fail because of changes made in the time between the developer pulled, made his changes and pushed back.
A rebase is essential but I would recommend starting with a fresh pull and copy all changes by hand instead of a rebase, this may be easier.

@ayman-alkom No, the master branch is for the latest stable versioned state of the app, not for development. It would not change any rebasing either.

**Comment by Kovah** [comment]
See #375

**Pull request closed without merging**
