### PR TITLE
#973: Bug fixes after a report in the comments of PR #973

### PR DESCRIPTION
**Pull request by nielsdrost7**

### CODE REVIEW

**Comment by nielsdrost7** [comment]
@Verony-makesIT thanks to the report you made in PR #973 I was able to make this pull-request:
https://github.com/InvoicePlane/InvoicePlane/pull/973#issuecomment-1704796301
Feel free to review it

**Comment by Verony-makesIT** [comment]
@nielsdrost7 
I have installed the 1.6.1 beta 3 version (incl. bugfix #973) and I have not noticed any issues related to xss_clean.

**Comment by nielsdrost7** [comment]
Thanks for the update.
If you run into anything that could be related to the update (mostly lots of fields have gotten dxtra checks, so test creating clients, invoice, the usual), just report it on the forums

**Comment by Verony-makesIT** [comment]
**FYI**, I previously reported a comment in Slack on the (v1.6.1 beta 3) notification from Clockwiseq **_regarding an (create user) error_** during the installation of version 1.6.1 beta 3.

**Pull request merged**
