### PR TITLE
[IP-109] Added selection menus to allow the user to select the PDF template

### PR DESCRIPTION
**Pull request by 749**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch. (v1.6.0)
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature 
  * [x] New Feature

_This is likely not the full fix for the issue, but hopefully a step in the right direction._

This PR adds a dropdown-submenu to the "Download PDF" so the user can choose the PDF at invoice/quote creation. The current system-default is highlighted by a chevron.

See image below for an example of what it adds to the system

image

### CODE REVIEW

**Comment by kintaro1981** [comment]
this is another PR related to #109 :
#334

**Comment by nielsdrost7** [comment]
https://development.invoiceplane.com/browse/IP-109 updated

**Comment by foegra** [comment]
Hello, what about this pull request?
This is something i miss a lot in the app.

**Comment by UnderDogg** [comment]
Hey @foegra,
We can't automatically merge this PR, it's failing one of the checks.
We're working on a new version and maybe I can bring in this feature, but I need to make sure all the checks are passing.

Hope you understand and thanks for bringing it to our attention

**Pull request merged**
