### PR TITLE
Fix setup Red Screen Of Death with bad DB query

### PR DESCRIPTION
**Pull request by sudwebdesign**
## Description
After tested (with real data backup of 1.5.11 version) i get an error 
CI say `Call to undefined method CI_DB_mysqli_driver::_error_message()`

+ Complete https://github.com/InvoicePlane/InvoicePlane/issues/1147
+ [Solve Red screen Of Death of bad DB query in
CI3](https://stackoverflow.com/questions/7843406/codeigniter-how-to-catch-db-errors#54519533)

+ Fix Call to undefined method CI_DB_mysqli_driver::_error_message()
The _error_message() function unexist in CI3.1.13:
`vendor/codeigniter/framework/system/database/DB_driver.php`

+ Indents: tab2spaces

## Motivation and Context
Does it solve a provlem with setup.
+ Now: All setup db query with error return a message and `Try again` button appear,
+ Before: 
++ `Call to undefined method CI_DB_mysqli_driver::_error_message()` or
++ Red Screen Of Death

## Screenshots (if appropriate):
To test:

+ 1 Remove in ip_version the fourth last lines
IP-remove-DB-ip_versions-1 5 12

+ 2 Go to index.php/setup and continue to upgrade_database
IP-upgrade_tables_errors_do_try-again

+ 3 Continue
IP-upgrade_tables_after-try-again

+ 4 **Rude Test** Remove all sql versions, (Just only 1.0.0 in list of `ip_version` table)
IP-upgrade_tables_errors_do_try-again-from-1 0 0
This is just end of page, but before are numerous errors, but if click on Try-again return same as image 3 (Continue).

## Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request.
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.

## Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature
  * [ ] New Feature

### CODE REVIEW

**Comment by sudwebdesign** [comment]
#idea 
A little script to go on bottom page on content loaded to be unafraid by CI errors?
```javascript
window.scrollTo(0, document.body.scrollHeight);
```
Js from:  https://stackoverflow.com/a/11715670

**Comment by nielsdrost7** [comment]
I like the solution.
But then after `Try again` will the upgrade continue?

I would rather (also) to update the database properly and then continue. I think the version 1.5.12 was missing from the versions table and that causes the problem.
- if (mysql error message 1160 or whatever)
- add 1.5.12 as version
- keep going and continue the rest of the tables
(Hope it makes sense)

**Comment by nielsdrost7** [comment]
This error only occurs when:
- the database update for 1.5.12 has been applied (ip_login_log table)
- but the version update has not been applied

and that's a very legitimate situation

**Comment by sudwebdesign** [comment]
hi, @nielsdrost7 
> But then after `Try again` will the upgrade continue?


With this, it apply only if sql query it applicable and have no error at first time (after `configure_database` step), only return _errors message(s) _ and  `Try again` button appear (and all of 0xx.1.x.x.sql missing at added in `ip_versions`) after click on `Try again` do nothing (speedy return) All possible (missing?) update applied, Click on continue go to `complete` (last) step. Click on Login Button and after Logged in it work like charm.


Note: The DB no stop on error because `$this->db->db_debug = false;` (this is the secret) 
and (maybe) the DB work this in `production` ENVIRONMENT?

**Comment by sudwebdesign** [comment]
@nielsdrost7 

>This error only occurs when ...

`Call to undefined method CI_DB_mysqli_driver::_error_message()`

Always if no error `$error['code'] === 0` (in My first test) and need sql to be upgrade app.
(or error different of 1050 or 1060)

Because The `_error_message()` function don't exist and make a fatal error. 
And if no error (code = 0) go to inside `if` _meaculpa_

With this solution, all error are returned to the user (No `DB` Red Screen Of Death).
User never blocked by setup.

Click `Try again` -> `Continue` -> `Login`

**Comment by sudwebdesign** [comment]
@nielsdrost7 
Have an idea:
[At line 55](https://github.com/InvoicePlane/InvoicePlane/pull/1160/files#diff-460b9297383c0b60b3fb51ad3a92b286c805e7ab186eb5db735121a695a6c16fR55)
```php
            $this->db->db_debug = false;
```
add `IP_DEBUG` like this:
```php
            $this->db->db_debug = IP_DEBUG;
```

Good idea?

**Comment by nielsdrost7** [comment]
> Good idea?

Yep, go for it

**Comment by sudwebdesign** [comment]
`IP_DEBUG` is in place.

**Comment by nielsdrost7** [comment]
I'll merge it and make the final 1.6.2 release.
Thank you very much @sudwebdesign !
You've saved the day!

**Pull request merged**
