### PR TITLE
V1.6.0

### PR DESCRIPTION
**Pull request by M4rt1n17**
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [x] Improvement of an existing Feature 
  * [ ] New Feature

Could you pls support PHP 7.3. Guess thats not a big thing to do, as all other webapps (which supported PHP 7.2) are able to run under PHP 7.3

### CODE REVIEW

**Comment by Kovah** [comment]
Pull requests are not for issues.

Visit https://community.invoiceplane.com/

**Comment by haseebnoor** [comment]
How to fix this error 






A PHP Error was encountered
Severity: 8192

Message: The each() function is deprecated. This message will be suppressed on further calls

Filename: MX/Modules.php

Line Number: 81

Backtrace:

File: C:\xampp1\htdocs\invoice\application\third_party\MX\Modules.php
Line: 81
Function: each

File: C:\xampp1\htdocs\invoice\application\third_party\MX\Loader.php
Line: 269
Function: load

File: C:\xampp1\htdocs\invoice\application\core\Base_Controller.php
Line: 72
Function: module

File: C:\xampp1\htdocs\invoice\application\core\User_Controller.php
Line: 25
Function: __construct

File: C:\xampp1\htdocs\invoice\application\core\Admin_Controller.php
Line: 20
Function: __construct

File: C:\xampp1\htdocs\invoice\index.php
Line: 327
Function: require_once

**Comment by spacecabbie** [comment]
This might not be  the place to ask for support do that here: https://community.invoiceplane.com/c/support

**Comment by Eckybrazzz** [comment]
Yes, this works. Solves most of the problems with PHP 7.3.
Currently, using 7.3.8 and have only small issues

**Comment by Eckybrazzz** [comment]
Hi there, want to make a pull request but to this one shows up only.

**Pull request closed without merging**
