### PR TITLE
Added custom field types functionality to InvoicePlane custom fields

### PR DESCRIPTION
**Pull request by visualcookie**

### CODE REVIEW

**Comment by visualcookie** [comment]
Somehow, this PR isn't right. Saw the files just now...

**Comment by visualcookie** [comment]
Should be fixed now.

**Comment by Kovah** [comment]
Please refer to issues or create a new one before submitting a pull request. Add the issue ID in the commit message too.
Reference: [IP-46](https://development.invoiceplane.com/browse/IP-46)

**Comment by visualcookie** [comment]
@Kovah Should I do it now or for the next PRs coming? Didn't knew that there's already a ticket for this. :D

**Comment by Kovah** [comment]
Do it for the next PR's please. And search for the issue and assign it to yourself to avoid duplicate work.

**Comment by visualcookie** [comment]
@Kovah Have you done it already? Fetched the latest changes and it's aready in ip_lang.php.

**Comment by Kovah** [comment]
Yes I just moved them.

**Comment by visualcookie** [comment]
Oh, okay. Thanks :smile:

**Pull request merged**
