### PR TITLE
Change of name in quotes templates (IP-583)

### PR DESCRIPTION
**Pull request by daniel89fg**
Se cambia el nombre a las plantillas pdf y public_web, para que sean más acordes con los presupuestos. Ya que antes ponian facturas.

------

It is renamed pdf and public_web templates, so that they are more in line with budgets. Since before they put invoices.

### CODE REVIEW

**Comment by daniel89fg** [comment]
application/views/quote_templates/pdf/InvoicePlane.php to application/views/quote_templates/pdf/QuotePlane.php

and

application/views/quote_templates/public/InvoicePlane_Web.php to application/views/quote_templates/public/QuotePlane_Web.php

**Comment by Kovah** [comment]
Uhm.. that does not make any sense. The template names are regarding the application name and not generic. The templates _provided by InvoicePlane_.

**Comment by daniel89fg** [comment]
Has no sense?. Because a quotation template, is named invoice ?. That confuses me. When I'm in the general configuration of the application, in the quotes section, in the templates puts InovicePlace, and makes me think that I'm using the invoice template, not the quotation.

**Comment by Kovah** [comment]
You could rename them to InvoicePlane Quotes.php and something, but not QuotesPlane.

**Comment by daniel89fg** [comment]
quotes

Is something like this no longer understandable? Whatever the name you put, works well.

**Comment by Kovah** [comment]
Yes but the name should not be quoteplane. InvoicePlane as the project and software name should stay in the name! Take InvoicePlane Quotes.php or whatever but not quotesplane.

**Comment by daniel89fg** [comment]
Perfect, ok.

**Pull request closed without merging**
