### PR TITLE
Add french template

### PR DESCRIPTION
**Pull request by ThierryHFR**
## Description
The format of French quotations and invoices varies slightly. I've created templates.

## Screenshots (if appropriate):
Invoice using the "InvoicePlane" template
facture-en
Invoice using the "InvoicePlane - fr" template
facture-fr

## Pull Request Checklist

  * [x ] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request.
  * [ x] I selected the corresponding branch.
  * [ x] I have rebased my changes on top of the corresponding branch.

## Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature
  * [x ] New Feature

### CODE REVIEW

**Comment by ThierryHFR** [comment]
I wonder if these changes shouldn't be incorporated into the French locale?

**Comment by naui95** [comment]
Thank you for the contribution. I don't think we currently have a way to manage different templates per locale. InvoicePlane (v1) ships with some basic templates and that it's it (at least for the moment). Users may eventually use other templates by following the steps shown in https://wiki.invoiceplane.com/en/1.6/templates/using-templates.

We should probably think of a way of handling this stuff @nielsdrost7, but for the moment there is no possibility (in my opinion) to merge this PR in the InvoicePlane codebase.

**Comment by nielsdrost7** [comment]
@ThierryHFR also from me: thank you for your contribution.
For V2 we'll think of something but as naui said: for V1 we can't incorporate your PR into this version.

However:
> I wonder if these changes shouldn't be incorporated into the French locale?
Exactement! (That's all the French I know, sorry).

Yes, if you see texts in the French translation that you want to change, head over to https://crowdin.com/project/fusioninvoice/fr
You'll have the opportunity to improve those translations.

Every time we make a new release, we download those improved translations and then send them in the .zip with the release.

Does that help?

**Comment by ThierryHFR** [comment]
> Thank you for the contribution. I don't think we currently have a way to manage different templates per locale. InvoicePlane (v1) ships with some basic templates and that it's it (at least for the moment). Users may eventually use other templates by following the steps shown in https://wiki.invoiceplane.com/en/1.6/templates/using-templates.
> 
> We should probably think of a way of handling this stuff @nielsdrost7, but for the moment there is no possibility (in my opinion) to merge this PR in the InvoicePlane codebase.

In fact, I don't agree with you at all. InvoicePlane provides everything you need to integrate templates, just give them different names and place them in the appropriate folder.

**Comment by nielsdrost7** [comment]
> In fact, I don't agree with you at all. InvoicePlane provides everything you need to integrate templates, just give them different names and place them in the appropriate folder.

We'll think of a way for V2 to make it more noticeable.
I think we got thrown off by the `- fr` suffix, because then tomorrow, someone comes and want to add `- it` or `- ch` as a suffix.

> I'll be working on options for positioning the blocks.

I'm really looking forward to that PR.
For now, I think you can keep it simple, by just making a setting
- company address fields on the left
- customer address fields on the right
or something like that.

But also think of something beautiful for V2, that would help a lot.

> Even if this is related to French for me, it's not translation but formatting.

The offer to help with the translations still stands.
To be honest, I had to look 3 timed for the differences, in that case, your layouts work and your PR is welcomed

**Comment by DineJ** [comment]
> The offer to help with the translations still stands.
> To be honest, I had to look 3 timed for the differences, in that case, your layouts work and your PR is welcomed

I'm closing this PR and making a new one quickly.

**Comment by ThierryHFR** [comment]
> > In fact, I don't agree with you at all. InvoicePlane provides everything you need to integrate templates, just give them different names and place them in the appropriate folder.
> 
> We'll think of a way for V2 to make it more noticeable. I think we got thrown off by the `- fr` suffix, because then tomorrow, someone comes and want to add `- it` or `- ch` as a suffix.
> 
> > I'll be working on options for positioning the blocks.
> 
> I'm really looking forward to that PR. For now, I think you can keep it simple, by just making a setting
> 
>     * company address fields on the left
> 
>     * customer address fields on the right
>       or something like that.
> 
> 
> But also think of something beautiful for V2, that would help a lot.
> 
> > Even if this is related to French for me, it's not translation but formatting.
> 
> The offer to help with the translations still stands. To be honest, I had to look 3 timed for the differences, in that case, your layouts work and your PR is welcomed

I'm closing this PR and making a new one quickly.

**Pull request closed without merging**
