### PR TITLE
Set proxy_ips from environment

### PR DESCRIPTION
**Pull request by j3k0**

### CODE REVIEW

**Comment by aalwash** [comment]
Thanks for contributing, please don't make PR's on the master, only on development branch

https://github.com/InvoicePlane/InvoicePlane/blob/master/CONTRIBUTING.md

**Comment by Kovah** [comment]
@j3k0 ?

**Comment by j3k0** [comment]
Sorry for the delay, it seems like the `development` branch is stalled, isn't it? Should I rebase upon one of the release branches?

**Comment by Kovah** [comment]
Pls use the 1.5.5 branch for this

**Pull request merged**
