### PR TITLE
Add attachments to pdf output invoice file

### PR DESCRIPTION
**Pull request by ykorzikowski**
I added the feature to merge attachments to output invoice pdf per default. Lets discuss if we should add a checkbox or similar to enable/disable this feature. 

I was not able to create an issue because the ssl cert of the issue tracker is not valid anymore

Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature 
  * [x] New Feature

### CODE REVIEW

**Comment by Kovah** [comment]
How are attachments handled which usually cannot be attached to PDFs, like .xlsx or .csv files? Was this properly tested?

**Comment by ykorzikowski** [comment]
Good point. I will check this to add only pdf and images.

**Comment by rein-10** [comment]
Hi, 

Can I used this code for quotes instead of invoices. If the answer is no, can you guide me so I can make the changes to attach files in quotes instead of invoices?

**Comment by ykorzikowski** [comment]
If course you can :)

Von meinem iPhone gesendet

**Comment by MartinH0** [comment]
To verify everything works as expected I created a Test-Release for everyone who wants to test this and report back if everything was working fine.

| Object        | Value |
| ------------- |-------------|
| name:     | v1.5.12-test-attatch.zip |
| md5:      | 0f754a0485bc909224962c2b4bf4b5b1| 
| sha256: |6f5e3817fbd02d2f5a8deb10f586a5a29fb13746d2cb2e8bb2db5b5d045ae4e6| 
| size:     |13.835 MiB |
| dl file (com):      |https://dl.invoiceplane.com/v1.5.12-test-attatch.zip |
| txt sums (com): |https://dl.invoiceplane.com/v1.5.12-test-attatch.zip.txt|

Feedback is needed for these cases:

1. does appending common Files (PDF) work?
2. what happens with uncommen Files (.xlsx) if they can not be appended?
3. what happens if I append more then 100MB is there a Limit defined or can the system be crashed with this functionallity?

I try to test it myself in the next days/weeks

**Comment by rein-10** [comment]
> Of course you can :) Von meinem iPhone gesendet
> […](#)
> Am 07.04.2020 um 23:05 schrieb rein-10 ***@***.***>: ﻿ Hi, Can I used this code for quotes instead of invoices. If the answer is no, can you guide me so I can make the changes to attach files in quotes instead of invoices? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I mirror almost everything (didnt change anything in the composer lock) to be able to add attachments to quote output but couldnt make it work. When ever I try the download with attachments button it will generate the pdf without the attachments. Could anyone point out what else I have to do or what am I doing wrong?

**Pull request merged**
