### PR TITLE
Improves file handling, adds file icons (IP-500)

### PR DESCRIPTION
**Pull request by denysvitali**
- Guests can now download files in `Invoiceplane_Web.php` view ([IP-500](https://development.invoiceplane.com/browse/IP-500))
- File uploaded (non images) have better icons (I made them myself, if you want me to share the `svg` / `ai` just let me know: License CC0)
screenshot from 2017-03-08 21-10-01

### CODE REVIEW

**Comment by Kovah** [comment]
Could we directly use SVGs for the file icons? They are smaller and scalable for resolutions > 2K and retina devices.

**Comment by denysvitali** [comment]
Yes, indeed. I wanted to use them but there might be some browsers that don't support them. Do you want to have retro-compatibility?

I'll add the changes requested, ASAP

**Comment by Kovah** [comment]
[SVGs](http://caniuse.com/#feat=svg) are supported by all major browsers and IE > 9 so I would prefer them over PNGs.

**Comment by denysvitali** [comment]
Will fix 👍

**Pull request merged**
