### PR TITLE
Improve email templates to support EmailToSMS services

### PR DESCRIPTION
**Pull request by jaskoola**
Purpose of this change is to support email to sms service to inform customer via sms. Service like smsapi.pl wants email like:

TO: sms.do@smsapi.pl
SUBJECT: login@8456fkty567gb3bg37b357b3457b3457
BODY: from=SMSAPI&to=48606605***&raport=1&message=TEKST WIADOMOSCI PRO

I added such fields to email template: to_email, send_pdf and send_attachments.

to_email is receiver email address. Can be fixed address like sms.do@smsapi.pl or {{{client_email}}}
send_pdf specify if invoice pdf should be generated and send
send_attachments specify if invoice attachments should be send

### CODE REVIEW

**Comment by Kovah** [comment]
If you haven't done it already: do a rebase first.

**Comment by Kovah** [comment]
@jaskoola ?

**Comment by jaskoola** [comment]
it is rebased and I submited IP-348.

**Comment by Kovah** [comment]
@jaskoola Please take a look at https://development.invoiceplane.com/browse/IP-353

**Pull request merged**
