### PR TITLE
add default_item_tax_rate setting to output - IP-481

### PR DESCRIPTION
**Pull request by pumpi**
The default setting has no effect i change this

### CODE REVIEW

**Comment by Kovah** [comment]
Please follow the [contribution guide](https://github.com/InvoicePlane/InvoicePlane/blob/master/CONTRIBUTING.md#3-contributing-code) and update this issue.

**Comment by Kovah** [comment]
@pumpi

**Comment by pumpi** [comment]
i have no time to do this at the moment can you do it by your self?

**Comment by pumpi** [comment]
i have create an issue but i cannot view
https://development.invoiceplane.com/browse/IP-480

**Comment by Kovah** [comment]
For some reason the security settings were set wrong for the issue. Created a new one.

**Pull request merged**
