### PR TITLE
PHP8.1 compatibility

### LINKED ISSUE #814: FEATURE - Stripe Integration Outdated
Stripe integration is outdated, I got error. Please update it according to their docs

_Originally posted by @anondev-sudo in https://github.com/InvoicePlane/InvoicePlane/issues/307#issuecomment-1143483550_

### PR DESCRIPTION
**Pull request by vtq221**
PHP8.1 compatibility changes - see #798 

https://php.watch/versions/8.1

Testing progress against PHP8.1
- [X] phpcompatibility/php-compatibility code scan for errors
- [X] Core functionality (login, session, view render, save form data, nav menu)
- [X] Modules: clients, quotes, invoices, payments products, tasks, reports
- [X] PDF creation
- [X] Email
- [X] System settings
- [X] Recurring invoices / cron
- [X] Create user
- [X] Custom fields
- [ ] Online payment - omnipay update and tests, check if resolves #814  or #757 

Pull Request Checklist

  * [X] My code follows the code formatting guidelines.
  * [X] I have an issue ID for this pull request. 
  * [X] I selected the corresponding branch.
  * [X] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature 
  * [ ] New Feature
  * [X] Compatibility with new software

### CODE REVIEW

**Review by nielsdrost7 — APPROVED** [review]

**Comment by virtiqa** [comment]
FYI there may be a few more issues related to PHP8.1's handling of null values - will do some testing and may end up making more commits

**Comment by onny** [comment]
Is a new offical release with PHP8 support planned any time soon? Looking forward to it otherwise we'll have to drop Invoiceplane from NixOS :,(

**Comment by clockwiseq** [comment]
> Is a new offical release with PHP8 support planned any time soon? Looking forward to it otherwise we'll have to drop Invoiceplane from NixOS :,(

Although we do not have a schedule or a date just yet, we are planning on releasing a new version that is compatible with PHP8 and we plan on staying compatible with the latest PHP releases going forward.  I know that doesn't really answer your question, but at least letting you know that we do plan on releasing a new version, just not scheduled yet.

**Comment by nielsdrost7** [comment]
@onny thank you for your question.

This PR _is_ that PHP 8.1 compatible version.
We can release it any time, but we're waiting for a tactically right time.

**Comment by WalleBE** [comment]
Hi, is it safe to use this version? My provider is stopping php 7.4 support.
I'm happy to test.

**Comment by vtq221** [comment]
> 

Hi there,

Testing would be great if you can take a look. Based on my testing it's working well but it would be good to get some more testers - I should have time to fix any specific issues identified. I don't have time right now to do thorough testing myself.

The only exception is online payments - I haven't had time to implement online payments for PHP8. It could take some time.

I'll do my best to resolves issues identified by testers, but unfortunately I've been very busy lately so haven't been able to thoroughly test myself. I've been using this version myself with no issues for several months.

If anyone needs online payments, maybe post which provider you use. Without more help, I won't be able to implement all the current supported payment providers.

**Comment by WalleBE** [comment]
Hi, I'm not using payments functions, I'll test standard function as deep as possible :-)

**Comment by nielsdrost7** [comment]
Thanks guys, really appreciate it!

**Comment by onny** [comment]
I don't use payments too and would be happy to use InvoicePlane with PHP8. I'm trying to package this pull request on NixOS for easier testing in maybe upgrading to this unstable release to avoid dropping it due to missing PHP8 support: https://github.com/NixOS/nixpkgs/pull/194059

I build it from source with
```
composer install
yarn build
yarn install
```

When opening Invoiceplane in the browser I get
```

Fatal error: Uncaught TypeError: Dotenv\Dotenv::__construct(): Argument #1 ($store) must be of type Dotenv\Store\StoreInterface, string given, called in /nix/store/fvcmmirjs4434624jbr0rlmla266q22q-invoiceplane-localhost-unstable-2022-08-08/index.php on line 18 and defined in /nix/store/fvcmmirjs4434624jbr0rlmla266q22q-invoiceplane-localhost-unstable-2022-08-08/vendor/vlucas/phpdotenv/src/Dotenv.php:60 Stack trace: #0 /nix/store/fvcmmirjs4434624jbr0rlmla266q22q-invoiceplane-localhost-unstable-2022-08-08/index.php(18): Dotenv\Dotenv->__construct() #1 {main} thrown in /nix/store/fvcmmirjs4434624jbr0rlmla266q22q-invoiceplane-localhost-unstable-2022-08-08/vendor/vlucas/phpdotenv/src/Dotenv.php on line 60
```

**Comment by nielsdrost7** [comment]
@onny did you make a copy of the ipconfig.php.example file to ipconfig.php?
It's thr first thing I'm thinking of when I see these types of errors

**Comment by onny** [comment]
Thank you for the fast feedback. Should be present. It is the kind of config I used in Invoiceplane 1.5.11. Not sure if something changed in the meantime
```
$ curl http://localhost/ipconfig.php
IP_URL=http://localhost
ENABLE_DEBUG=false
DISABLE_SETUP=false
REMOVE_INDEXPHP=false
DB_HOSTNAME=localhost
DB_USERNAME=invoiceplane
# NOTE: file_get_contents adds newline at the end of returned string
DB_PASSWORD=
DB_DATABASE=invoiceplane
DB_PORT=3306
SESS_EXPIRATION=864000
ENABLE_INVOICE_DELETION=false
DISABLE_READ_ONLY=false
ENCRYPTION_KEY=
ENCRYPTION_CIPHER=AES-256
SETUP_COMPLETED=false
```

**Comment by nielsdrost7** [comment]
Nothing changed. Config looks good.
It's something else and it needs some debugging

**Comment by nielsdrost7** [comment]
@onny can you move phpdotenv back to an older version?
> `"vlucas/phpdotenv": "^3.4.0"`

**Comment by WalleBE** [comment]
Hi, I cannot find the vendor-folder in the repository. Is it safe to use the folder from V 1.6.11?
If I do, I got this fault: Fatal error: Uncaught Error: Call to undefined method Dotenv\Dotenv::createImmutable() in /data/sites/web/www/ip_8/index.php:19 Stack trace: #0 {main} thrown in /data/sites/web/www/ip_8/index.php on line 19

**Comment by nielsdrost7** [comment]
@WalleBE usually these types of questions go on the forums or in the slack channels, but I'll let it slide for this time. I've created a github issue for you, so you can receive your answer.

Right now, here, we comment on the Pull-request, that gets us to PHP8 compatibility. Let's keep it that way

**Comment by onny** [comment]
> @onny can you move phpdotenv back to an older version?
> 
> > `"vlucas/phpdotenv": "^3.4.0"`

Oh sorry it seems it was my mistake. I patched index.php file in my NixOS module to override custom options/settings https://github.com/NixOS/nixpkgs/blob/fd54651f5ffb4a36e8463e0c327a78442b26cbe7/nixos/modules/services/web-apps/invoiceplane.nix#L42

There I used the dotenv function which doesn't seem to be compatible with the latest version of it. I need to fix this myself. On the other side Invoiceplane seems to work with PHP8.1 using this branch. Hope the development gets merged into master soon so we can start testing and fixing bugs :)

**Comment by onny** [comment]
For me it works with phpdotenv at the latest version. Version 3.4 won't probably work because it doesn't support PHP8

**Comment by nielsdrost7** [comment]
@vtq221 @onny could you guys please contact me on our slack channels this weekend? I would love to go over some things with you
https://join.slack.com/t/invoiceplane/shared_invite/zt-sjirc9h2-952baR9rn4r8LyzRK9MveA

**Comment by onny** [comment]
Thank you for merging :) Is this already in master or develop branch?

**Comment by nielsdrost7** [comment]
@onny it's in `development` branch for now

**Pull request merged**
