### PR TITLE
[IP-512] Implement template files for emails

### PR DESCRIPTION
**Pull request by daniel89fg**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [ ] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature 
  * [x] New Feature

### CODE REVIEW

**Comment by Kovah** [comment]
Please please please sign up for the issue tracker and assign all issues you are working on to you and **please ask before implementing larger features like this**.

I already made some planning for this and I'm afraid to say that this might be not the correct implementation for this feature as I don't see any changes in the email sending form and the email templates does not look that good either.

**Comment by daniel89fg** [comment]
> Please please please sign up for the issue tracker and assign all issues you are working on to you and please ask before implementing larger features like this.

How do I do this?

> I already made some planning for this and I'm afraid to say that this might be not the correct implementation for this feature as I don't see any changes in the email sending form and the email templates does not look that good either.

From the general settings you can edit colors and texts of the email template. And the already designed emails are integrated into the template in the white box.

email

**Comment by Kovah** [comment]
> How do I do this?

Sign up for the issue tracker at development.invoiceplane.com and I will add you to the developers group.

> From the general settings you can edit colors and texts of the email template. And the already designed emails are integrated into the template in the white box.

That's not what the email feature should be. Email templates should **replace** the whole message entirely. No WYSIWYG editor or HTML in the email message, no settings to set your colors or similar stuff. The user should do everything within the HTML template **like with the PDF files**. The user _may_ specify an additional message that is displayed in the email but the main content (client, invoice or user data) is processed and displayed in the template file itself.

**Comment by daniel89fg** [comment]
OK no problem. I'm already registered at development.invoiceplane.com

**Comment by Kovah** [comment]
PR will most likely be closed in favor of the correct implementation, with some of the changes from this PR being adapted.
Keep it open for now.

**Pull request closed without merging**
