### PR TITLE
Fix bug with recurring invoices dropping discounts

### PR DESCRIPTION
**Pull request by pimvanpelt**
Fix for #790

Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature 
  * [ ] New Feature

### CODE REVIEW

**Comment by nielsdrost7** [comment]
In the issue you want to change `application/modules/invoices/models/Mdl_invoices.php`, but in the commit you have changed `application/modules/invoices/controllers/Cron.php`?

**Comment by pimvanpelt** [comment]
Second comment in #791 :
"""As a partial (perhaps sufficient) fix - we can copy forward these two specific fields in invoices/controllers/Cron.php which I'll do now. PR incoming!"""

I figured that the less likely intrusive fix would be to leave the shallow copy_invoice() where it was, and address the fix in the place where the copy happens (Cron.php).

I'm not super familiar with your codebase - feel free to reject the PR and fix in Mdl_invoices.php if you feel that's a better place. Certainly, the edit in Cron.php does address the issue with recurring invoices.

**Comment by nielsdrost7** [comment]
I'm willing to go with your fix in the Cron controller, but I must be missing something.
Screenshot from 2022-01-04 17-51-31
that's the only fix I see.

**Comment by pimvanpelt** [comment]
That change is sufficient -- for each new recurring, the code in Cron.php first gets the original (base) invoice:

```
            // This is the original invoice
            $invoice = $this->mdl_invoices->get_by_id($source_id);

```

And then it creates a new invoice with all sorts of info from that base invoice (now also including the discounts:
```
            // Create the new invoice
            $db_array = array(
                'client_id' => $invoice->client_id,
                'invoice_date_created' => $invoice_recurring->recur_next_date,
                'invoice_date_due' => $this->mdl_invoices->get_date_due($invoice_recurring->recur_next_date),
                'invoice_group_id' => $invoice->invoice_group_id,
                'user_id' => $invoice->user_id,
                'invoice_number' => $this->mdl_invoices->get_invoice_number($invoice->invoice_group_id),
                'invoice_url_key' => $this->mdl_invoices->get_url_key(),
                'invoice_terms' => $invoice->invoice_terms,
                'invoice_discount_amount' => $invoice->invoice_discount_amount,
                'invoice_discount_percent' => $invoice->invoice_discount_percent
            );

            // This is the new invoice id
            $target_id = $this->mdl_invoices->create($db_array, false);
```

And indeed, based on an original invoice:
Screen Shot 2022-01-04 at 18 20 33

The derived recurring invoice does apply the discount:
Screen Shot 2022-01-04 at 18 27 51

Isn't that all we need?

**Comment by nielsdrost7** [comment]
ok. Approved. Thanks for the PR, man!

**Comment by nielsdrost7** [comment]
closes #790

**Pull request merged**
