### PR TITLE
feat: payment QR code for web/pdf templates

### PR DESCRIPTION
**Pull request by mheiduk**
## Description
Adding payment QR code feature for web/pdf invoice templates. Due to the pull request https://github.com/InvoicePlane/InvoicePlane/pull/987 redesigning the default invoice templates, I didn't add the QR code image to the invoice templates just yet. Tested it with the current ones though. If you want it in the current invoice templates anyway, then I can add it.

For testing just add the following helper function inside web/pdf templates:
```
<?php echo invoice_qrcode($invoice->invoice_id); ?>
```

## Related Issue
Forum thread: https://community.invoiceplane.com/t/topic/9627/3

## Motivation and Context
I need this feature for a client. Furthermore it is quite common today to pay with QR code via banking apps.

## Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request.
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.

## Issue Type (Please check one or more)

  * [ ] Bugfix
  * [ ] Improvement of an existing Feature
  * [x] New Feature

### CODE REVIEW

**Comment by nielsdrost7** [comment]
@mheiduk 

Thanks for the PR, man!
> If you want it in the current invoice templates anyway, then I can add it

Yes, please add it.

I'll take a look very soon at the rest of the PR.

**Comment by mheiduk** [comment]
> @mheiduk
> 
> Thanks for the PR, man!
> 
> > If you want it in the current invoice templates anyway, then I can add it
> 
> Yes, please add it.
> 
> I'll take a look very soon at the rest of the PR.

Sure! QR code image and payment info added to the invoice templates.

**Comment by Verony-makesIT** [comment]
@mheiduk, I would like to test/use your QRcode feature but I can’t find a decent explanation of it anywhere.
More specifically, I would like to know **where in my template file(s)** I can adjust and/or set the QrCode settings?
Currently I would like to know where I can adjust or set the height and width, foreground and background colors, border and margin and possibly also if a logo is possible in the QrCode?
_Some examples would already help._

**Comment by mheiduk** [comment]
> @mheiduk, I would like to test/use your QRcode feature but I can’t find a decent explanation of it anywhere. More specifically, I would like to know **where in my template file(s)** I can adjust and/or set the QrCode settings? Currently I would like to know where I can adjust or set the height and width, foreground and background colors, border and margin and possibly also if a logo is possible in the QrCode? _Some examples would already help._

Sorry for the late reply. You can find the QR-Code settings in System Settings > Invoices -> QR Code settings. There you can set the recipient, IBAN, BIC and remittance text. Height and width of the QR code is changable via CSS `#invoice-qr-code`. Foreground and background colors and a custom logo inside of the QR code is not supported yet. But it would be a nice addition imo. You could create an issue and I would look into it.

**Comment by Verony-makesIT** [comment]
@mheiduk,  
Thanks for this answer, but I am going to stick (_for now?_) with the old and integrated (barcode - QRcode) solution in mPDF, which is clearer, more flexible and easier to handle/use **for me**.

**Pull request merged**
