### PR TITLE
[IP-717] Implements hotfix for item discount calculation

### PR DESCRIPTION
**Pull request by Kovah**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature 
  * [ ] New Feature

---

Quotes / invoices created after the update to 1.5.10 will get a modifier that enables the new discount/tax calculation. This way old invoices are not recalculated but new ones will use the correct calculation method. Credits go to @mjmunger.

### CODE REVIEW

**Comment by Kovah** [comment]
@mjmunger Would you like to take a look into this?

**Comment by mjmunger** [comment]
Happy to check it out a little later today. Finishing up unit tests for a package that works with InvoicePlane's database, so I have use cases ready to go.

**Comment by mjmunger** [comment]
Took a quick look at it just now... do you mind if I clean this up?

**Comment by Kovah** [comment]
Sure, feel free to propose changes. It's a quick and dirty solution.

**Comment by mjmunger** [comment]
I've refactored a bunch of things. I am not sure how you want to receive the changes. Obviously, I don't have push rights to your local fork (that would be most convenient). How do you want to do this?

**Comment by Kovah** [comment]
You may send the patch file to mail@invoiceplane.com so I can apply the changes you made.

**Comment by mjmunger** [comment]
Patch submitted. Updates are in the CHANGELOG.md, which I have added (not sure why it wasn't there before?)

**Comment by Kovah** [comment]
@mjmunger I implemented your new calculation approach for quotes. However, the `QuoteItemBase` has a flaw which cause I couldn't find. I added a comment explaining what's wrong. Maybe you could take a look at it?

**Comment by mjmunger** [comment]
I did not pull your current verison to work with since I am already famliar with the changes needed, I just re-did it from my copy here. Sending you the patches now.

**Comment by mjmunger** [comment]
Anything else that needs to be done? Or can we publish v1.5.10?

**Comment by Kovah** [comment]
If it's working correctly version 1.5.10 can be published.

**Comment by mjmunger** [comment]
I'll pull and test.

**Comment by mjmunger** [comment]
Doing a pull / test now. Will advise in 30 minutes.

**Comment by mjmunger** [comment]
Revision 0a113a17 has the autoloader I put in pre-maturely removed. Composer does handle autloading for composer compliant packages, but these classes are not a composer compliant package, so Composer doesn't now about them.

Moving `src` to `applications/` is a somewhat valid choice, so we can keep it, but the `autoload.php` file needs to be put back, and the path where the autoloader looks needs to be updated to `applications/src/`.

Having fixed this in dev, the invoices are not calculating correctly again. :-(

**Comment by Kovah** [comment]
Classes are loaded correctly after running `composer install`.

**Comment by Kovah** [comment]
@mjmunger  Are there any news on the testing?

**Comment by mjmunger** [comment]
It's on my list, but I haven't been able to get to it. We do billing once / month, so it is about to get more important very soon.

**Comment by Kovah** [comment]
@miquel-cabanas Could you help me out here? Would just need a check of quotes / invoices to be working correctly. Would like to publish 1.5.10 in the next week(s). :)

**Comment by mjmunger** [comment]
We've got it working internally, and it is a priority for us to push this out to you, but we have to get a few things handled on the business side first. Will try to do this in the next couple days.

Get Outlook for Android<https://aka.ms/ghei36>




On Sun, Sep 9, 2018 at 3:27 AM -0400, "Kovah" <notifications@github.com<mailto:notifications@github.com>> wrote:


@miquel-cabanas<https://github.com/miquel-cabanas> Could you help me out here? Would just need a check of quotes / invoices to be working correctly. Would like to publish 1.5.10 in the next week(s). :)

**Comment by miquel-cabanas** [comment]
I am currently checking the language issue reported in IP-531. I think it is fixed, but when investigating it I have found another minor language problem. When I'm done with it I will have a look at this PR.

**Comment by Kovah** [comment]
Funding will be split 50:50 for development and testing.
75% go to @mjmunger 
25% go to a user who does additional testing.

**Comment by Kovah** [comment]
I would like to publish 1.5.10 with this fix on the upcoming sunday (2018-10-07).
Therefore I will do additional testing with various versions and states. Clean install and existing databases.

**Comment by miquel-cabanas** [comment]
There is a minor issue in the function `get_item_discount_total()` in file `application/src/ItemBase.php` that does not affect the calculations, but may cause confusion in the future:

* rename `$tax_total` as `$discount_total`

```php
public function get_item_discount_total()
{
    $quantity = (int)round($this->item_quantity * 100, 2);
    $discount = (int)round($this->item_discount_amount * 100, 2);
    $tax_total = $quantity * $discount / 100 / 100;
    return $tax_total;
}
```

I will keep reviewing the code and will comment anything I found, although, from what I have read so far, I suspect they will be just minor issues like this one.

**Comment by miquel-cabanas** [comment]
Sorry to be picky :pray: but the names of files, classes and variables do not seem to abide to CI conventions:

* [File Naming](https://www.codeigniter.com/user_guide/general/styleguide.html#file-naming)
* [Class and Method Naming](https://www.codeigniter.com/user_guide/general/styleguide.html#class-and-method-naming)

For instance, the file `ItemBase.php` should be renamed as `Item_base.php` and the class `ItemBase`should be renamed as `Item_base`.

On the other side, variable names seems to be fine

* [Variable Names](https://www.codeigniter.com/user_guide/general/styleguide.html#variable-names)

There's no need to change them to test the code since CI does not seem to be enforcing its standards as of now, but the names should be changed before accepting the pull request just in case a future version of CI becomes more strict.

**Comment by miquel-cabanas** [comment]
Good news! I am picky again :pray: which means I'm finding nothing really serious to comment :wink:

Some functions in `invoices/controllers/ajax.php` are still using `echo json_encode($response);` instead of the new `$this->respond($response);` but that could be fixed by a later pull request.

Other than this, I think the changes in this file are ok.

**Pull request merged**
