### PR TITLE
Update payment_handler.php

### PR DESCRIPTION
**Pull request by lemankk**
Hotfix: update issue #IP-399 about missing description text when a payment completed.

### CODE REVIEW

**Comment by alwaysontop617** [comment]
Cool

**Comment by rohitchhetri** [comment]
mine pay now is not working is that because of payment_handler ?

**Comment by Kovah** [comment]
@lemankk please take a look at the [Contribution Guidelines](https://github.com/InvoicePlane/InvoicePlane/blob/master/CONTRIBUTING.md#3-contributing-code)
It's the wrong branch and the issue is missing.

**Comment by lemankk** [comment]
@Kovah thanks for remind and i re-create the pull request under 'development' branch.

**Pull request closed without merging**
