### PR TITLE
Use country key instead of country value for user-country setting

### PR DESCRIPTION
**Pull request by miquel-cabanas**
Use the country code ($cldr key in $countries array) in the forms when setting the country option and saving it to the database so that it is unaffected by changes to the application language.

### CODE REVIEW

**Comment by Kovah** [comment]
Looks good.
@Jadaw1n any objections?

**Comment by Jadaw1n** [comment]
What happens with the existing language setting? Should be converted if possible. (if not possible, mention it bright red in the setup)

**Comment by miquel-cabanas** [comment]
Making the user_country a required field in the user settings form could solve the problem.

In an existing installation the database contains the country-value. On the general settings form the country name is selected based on the language-cldr and correctly displayed in that language, but saving the settings from that page only affects the ip_settings table in the database, and does not touch the ip_users.user_country field. And on the user settings form the country field contains nothings and the user has to set again the country and save it.

To avoid users saving an empty country field, I have added a validation rule to make it a required field. The funny thing is that when attempting to save an empty country field the application complains and then **the country field displays the correct country name** and that it suffices to push again the save button to get the right country-key in the database. Thus, making the user_country a required field in the user settings form seems to solve the problem.

Miquel

**Comment by miquel-cabanas** [comment]
Sorry for the mess, I've learnt the hard way that, if there is already a pull-request in a branch, Github appends new commits to that brach into the existing pull-request. That's why I have reverted the commit, created a new branch called "fix_cancel_button_bug", and made the commit to it, and then a new pull-request.

**Comment by Kovah** [comment]
@miquel-cabanas Why did you closed the pull request?

**Comment by miquel-cabanas** [comment]
Ooops!  still learning git/github :-(  I wanted to update my development branch to the upstream one, thus I renamed it as development-old and then created a copy of upstream/development. I didn't think the pull-request would be gone, I (wrongly) assumed that it would be still around.

I will redo the commit to a feature-specific branch and then will make a new pull-request.

Miquel

**Pull request closed without merging**
