### PR TITLE
IP-612 Fixed Mollie payments

### PR DESCRIPTION
**Pull request by laemol**
Only tested with Mollie payment gateway. 
https://community.invoiceplane.com/t/topic/4625/23

### CODE REVIEW

**Comment by firstred** [comment]
Just tested this pull request and it fixed the Mollie payment gateway in my Invoiceplane instance.

**Comment by Kovah** [comment]
@firstred Thank you for the testing! Did you also check another payment method like PayPal?

**Comment by firstred** [comment]
@Kovah I have not. Does Invoiceplane connect with PayPal via Omnipay, too?

**Comment by firstred** [comment]
Let me test Stripe first. This looks like a fix for Stripe as well.

InvoicePlane uses the legacy NVP/SOAP API for PayPal Express. I don't think it is affected by this PR.

**Comment by firstred** [comment]
Ahh great, PayPal Express is on the Omnipay list as well. Nice, that must be easy to maintain! I'll test that as well. Will let you know the results.

**Comment by firstred** [comment]
Stripe seems to work, before and after this change. I was unable to test PayPal as my account no longer allows NVP/SOAP connections (time to add PayPal REST?)

I think it's safe to say that this pull request can be merged.

**Comment by Kovah** [comment]
@firstred Thank you very much! 👍 
Will take a look at the PayPal issue.

**Pull request merged**
