### PR TITLE
Update Mdl_custom_fields.php

### PR DESCRIPTION
**Pull request by DavidHazeldenUK**
Client Form won't load without adding 0.

### CODE REVIEW

**Comment by aalwash** [comment]
Your fix is wrong, because every loop is going to overwrite the previous (index 0) record.

Probably you have an error somewhere else and you thought this fixes it.
Which version of pho do you have?

**Comment by DavidHazeldenUK** [comment]
I have the latest release version, even the latest Github version still throws that error.
Currently I'm running it with a "0", and it's fine.
5.6 currently.
Will look at running it on 7.1+

**Comment by DavidHazeldenUK** [comment]
https://wptavern.com/php-5-6-is-now-the-most-widely-used-php-version

**Comment by Kovah** [comment]
The patch is included in version 1.5.5 which will be released once there are enough patches to justify the work related to a new release.

**Pull request closed without merging**
