### PR TITLE
(IP-684) Multi uploads

### PR DESCRIPTION
**Pull request by daniel89fg**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [ ] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [ ] Bugfix
  * [x] Improvement of an existing Feature 
  * [x] New Feature

### CODE REVIEW

**Comment by daniel89fg** [comment]
The images uploaded to the products can be viewed and viewed in large from the index of products. Very useful to see the photos of the products without having to enter inside each product.

**Comment by Kovah** [comment]
Okay, please remove both the js and css files for fancybox. External tools and libraries are implemented using NPm and not with their files in our repo. I will take care of this then.

**Comment by daniel89fg** [comment]
ready

**Comment by Kovah** [comment]
Could you please make two separate pull requests? I would not like to mix two different issues in on request.
Correct issue id for the product uploads is https://development.invoiceplane.com/browse/IP-550

**Pull request closed without merging**
