### PR TITLE
Updating build paths.

### PR DESCRIPTION
**Pull request by jdrich**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [ ] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature 
  * [ ] New Feature

Not sure if this is the correct dest branch, noticed this while building CSS initially.

### CODE REVIEW

**Comment by Kovah** [comment]
What exactly is the bug with this? Working fine for me.

**Comment by jdrich** [comment]
I'm getting the error here:

Running "sass:build" (sass) task
>> Error: File to import not found or unreadable: ../../../node_modules/dropzone/src/dropzone.
>>        Parent style sheet: /<>/InvoicePlane/assets/invoiceplane/sass/style.scss
>>         on line 20 of assets/invoiceplane/sass/style.scss
>> >> @import "../../../node_modules/dropzone/src/dropzone";
>>    ^

**Comment by kalimerre** [comment]
In my opinion it's more a path problem with ../../../ than src to dist.
In dist it's a CSS file 
In src it's a SCSS file and it's a sass:build means he will build it into CSS.

Which OS are you using ? 
How do you download the project ?

**Comment by jdrich** [comment]
Developing on Ubuntu, downloaded via git.

My dropzone module does not have a src directory.

**Comment by kalimerre** [comment]
Hmm
Maybe it’s because of an update. I will have a look. Which installation
guide you follow ?

Le jeu. 15 mars 2018 à 20:29, Jonathan Rich <notifications@github.com> a
écrit :

**Comment by jdrich** [comment]
https://github.com/InvoicePlane/InvoicePlane/blob/master/CONTRIBUTING.md

**Comment by kalimerre** [comment]
Thanks. Will try to reproduce it tonight ;).

**Comment by jdrich** [comment]
Good insight. Looks like 5.4.0 of dropzone removes the src directory. I'll leave it to you guys whether you want to lock versions. Would you like me to close this PR?

**Comment by kalimerre** [comment]
Keep it open for now. Either we use your solution or we lock the package to an outdated version up to @Kovah ;).

**Comment by kalimerre** [comment]
What I found : it has been upgraded in January from 4.3.0 to 5.3.0 (https://github.com/InvoicePlane/InvoicePlane/commit/e163d79fa2466a9abf31825c0a3056c38b75d367).

And indeed it has been changed to dist instead of src (**didn't test myself**!)

One of the changelog talking about dist : https://gitlab.com/meno/dropzone/blob/master/CHANGELOG.md#anchor-501


I saw many libraries using dist instead of src (example : https://github.com/rowanwins/vue-dropzone/pull/51/files or https://github.com/rowanwins/vue-dropzone/issues/185#issuecomment-340471677) 

So I think the PR can be approved if testing is working. Seems a good solution for me :)

**Pull request merged**
