### PR TITLE
1.5.5

### PR DESCRIPTION
**Pull request by daniel89fg**

### CODE REVIEW

**Comment by Kovah** [comment]
You can ignore `Method name Mdl_User_Clients::GetUsersAllClients is not in camel caps format` warnings

**Comment by daniel89fg** [comment]
The "errors" that remain, I do not know how to correct them.

**Comment by daniel89fg** [comment]
@Kovah can you remove this pull and start over, trying to be more orderly ?. Thanks.

**Comment by Kovah** [comment]
Yes, please open a new pull request. I will disable the formatting check but please add the htaccess and ipconfig.php.example files again.

**Pull request closed without merging**
