### PR TITLE
[IP2-62] Email form requires CC / BCC fields

### PR DESCRIPTION
**Pull request by dploeger**
Pull Request Checklist

  * [x] My code follows the code formatting guidelines.
  * [x] I have an issue ID for this pull request. 
  * [x] I selected the corresponding branch.
  * [x] I have rebased my changes on top of the corresponding branch.
  
Issue Type (Please check one or more)

  * [x] Bugfix
  * [ ] Improvement of an existing Feature 
  * [ ] New Feature

### CODE REVIEW

**Comment by Kovah** [comment]
Hi!
I think this was already resolved in #634. Could you check that?

**Comment by dploeger** [comment]
Yes, missed that. Sorry. Although it seems that #634 has a mistake. I commented that just now.

**Comment by harrysudana** [comment]
Hi,

i change a little and works for me.

```
public function create($object, $input)
    {
        if (!array_key_exists('cc', $input)) {
           $input['cc'] = [];
        }

        if (!array_key_exists('bcc', $input)) {
            $input['bcc'] = [];
        }

        return $object->mailQueue()->create([
            'from' => json_encode(['email' => $object->user->email, 'name' => $object->user->name]),
            'to' => json_encode($input['to']),
            'cc' => json_encode($input['cc']),
            'bcc' => json_encode($input['bcc']),
            'subject' => $input['subject'],
            'body' => $input['body'],
            'attach_pdf' => $input['attach_pdf'],
        ]);
    }
```

**Comment by dploeger** [comment]
@harrysudana I don't think, you need to change that, because that way, errors from "json_encode"ing $input['cc'] would result in a crash instead of an empty array. My PR should actually just work. Didn't it for you?

**Comment by Kovah** [comment]
Reward will be paid out to @dploeger

**Comment by dploeger** [comment]
Wow! Thank you very much. I never expected that for 8 loc 😉

**Pull request merged**
