### PR TITLE
fix real path for windows

### PR DESCRIPTION
**Pull request by kalimerre**
It miss the realpath function for the customer files folder so the condition was not met on Windows 

> C:\wamp64\www\invoiceplane\uploads/customer_files

instead of 

> C:\wamp64\www\invoiceplane\uploads\customer_files

Be careful ! I didn't test it on a Linux server only on my Windows be sure to test it before merge it 
To see if it works just go on a guest invoice URL with an attachment and try to download it.

### CODE REVIEW

**Comment by aalwash** [comment]
The real fix should be here: https://github.com/InvoicePlane/InvoicePlane/blob/3cd04a62bff7e7b8727b9aef2f5b5939d775ab34/index.php#L314

define('UPLOADS_FOLDER', FCPATH . 'uploads/');
define('THEME_FOLDER', FCPATH . 'assets/');

Both constants have /, instead of DIRECTORY_SEPARATOR

**Comment by kalimerre** [comment]
Indeed @aalwash you're right nice catch. 
I've added a commit to fix it in index.php and change Get.php

**Comment by aalwash** [comment]
👍

**Comment by Kovah** [comment]
Ah, saw this too late. Already fixed with 7d5d229ee8832a0750dc93e1c0023b7d7b42db61

**Pull request closed without merging**
